### PR TITLE
fix: sendTo uses shared connection - part 2: making sure messages get…

### LINKED ISSUE #25: Wrong topicIDs when sending a direct message
As I started debugging what's causing https://github.com/orbitdb/orbit-db/issues/258, I found out that when sending direct messages, we **sometimes** have the wrong topicID in our topicIDs array. 

If I'm not mistaken, the peer connection is shared between rooms (topics), so when we send a direct message to the peer, it might end up getting handled in a different room instance. This is, I believe, because of the `_handleDirectConnection()` [pulls directly](https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/src/index.js#L135) from the (shared-between-rooms) connection and as such, the handler being used can be the one created in room A while the message was sent via room B. So essentially, when we set `topicCIDs: [ this._topic ]`, *this* is not actually tied to the topic.

I'm not sure how we should fix this. It feels to me as it is today, it's breaking the *room* abstraction (a direct message sent from one room can "appear" in another), but then again, sending a direct message to a peer on the abstraction level doesn't necessarily need to be tied to a particular room. One solution would be to change the `sendTo()` method so that it creates a proper PubSub message [like we do on the receiving end](https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/src/index.js#L145), that way we can tie the room (topic) ID to the direct message. 

The question is, do we want that? Do we want the direct messages be per-room, or do we want them to be per-user/connection?

Any thoughts @pgte?

### PR DESCRIPTION
**Pull request by pgte**
… delivered to the correct rooms by using a global handler. Should fix #25

### CODE REVIEW

**Comment by pgte** [comment]
Kudos to @haadcode for spotting and providing a test case for this one again.
Do you mind reviewing / testing if this fixes it for you?

File: src/index.js [hunk 1]
```diff
@@ -82,7 +85,8 @@ class PubSubRoom extends EventEmitter {
     const seqno = Buffer.from([0])
 
     const msg = {
-      from: this._ipfs._peerInfo.id._idB58String,
+      to: peer,
+      from: this._ipfs._peerInfo.id.toB58String(),
```
Comment (haadcode) [inline src/index.js]: This comment is not for this line, but for the `if (!conn)` block above:
We should add `this._connections[peer] = conn` at the end of the block so that we have the connections when calling `leave()` in order to close the connection.

Comment (pgte) [reply src/index.js]: @haadcode good catch!
Should be fixed by cbe2c3ad532913bd131028a3ac948d6b7e890f24

**Comment by haadcode** [comment]
LGTM!

**Comment by haadcode** [comment]
And to clarify: it fixes the problem :) Ready for merge from my side. 🎉 thanks @pgte!

**Comment by pgte** [comment]
@haadcode thanks for the tip, test and review!
Landed on v1.0.1.
